version: 1.0.{build}

environment:
  COVERALLS_REPO_TOKEN:  
    secure: 3s1g47OKQnZfUMhJ3AxowogUmpv2K/Z4/DgmP0rGURItOyPitUIOEX1dfk3SkJvN

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

configuration: Release

#branches:
#  only:
#    - master
#    - development

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
before_build:
  - nuget restore src/Budgerigar.sln

build:
  verbosity: minimal
  project: src\Budgerigar.sln
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages

after_test: 
    - src\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[Budgerigar*]* -[Budgerigar.Tests]*" -target:"src\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"src\Budgerigar.Tests\bin\Release\Budgerigar.Tests.dll -appveyor -noshadow" -output:coverage.xml
    - src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover -f -r %COVERALLS_REPO_TOKEN% coverage.xml

deploy:
  provider: NuGet
  api_key:
    secure: +AIEY0E9rURDXqzW7YM/RoRXDhOxdTZQ4XyUxNCKR6zaHvj7ha/uZHnhqofdaUu3
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
   branch: master